import type { MeshPhysicalMaterialParameters } from 'three'
import type { MetalPreset } from '../types/index.ts'

export const METAL_PRESETS: Record<MetalPreset, MeshPhysicalMaterialParameters> = {
  polishedGold: {
    color: '#FFD700',
    metalness: 1.0,
    roughness: 0.05,
    clearcoat: 0.3,
    clearcoatRoughness: 0.05,
    envMapIntensity: 1.5,
  },
  polishedSilver: {
    color: '#C0C0C0',
    metalness: 1.0,
    roughness: 0.05,
    clearcoat: 0.3,
    clearcoatRoughness: 0.05,
    envMapIntensity: 1.5,
  },
  chrome: {
    color: '#FFFFFF',
    metalness: 1.0,
    roughness: 0.0,
    clearcoat: 1.0,
    clearcoatRoughness: 0.0,
    envMapIntensity: 2.0,
  },
  brushedSilver: {
    color: '#C0C0C0',
    metalness: 1.0,
    roughness: 0.35,
    clearcoat: 0.1,
    clearcoatRoughness: 0.2,
    envMapIntensity: 1.2,
    anisotropy: 0.8,
  },
  brushedGold: {
    color: '#FFD700',
    metalness: 1.0,
    roughness: 0.35,
    clearcoat: 0.1,
    clearcoatRoughness: 0.2,
    envMapIntensity: 1.2,
    anisotropy: 0.8,
  },
  roseGold: {
    color: '#B76E79',
    metalness: 1.0,
    roughness: 0.08,
    clearcoat: 0.3,
    clearcoatRoughness: 0.05,
    envMapIntensity: 1.5,
  },
  platinum: {
    color: '#E5E4E2',
    metalness: 1.0,
    roughness: 0.12,
    clearcoat: 0.2,
    clearcoatRoughness: 0.1,
    envMapIntensity: 1.3,
  },
  antiqueBronze: {
    color: '#CD7F32',
    metalness: 1.0,
    roughness: 0.4,
    clearcoat: 0.0,
    envMapIntensity: 1.0,
  },
}
