import type { PublicTrophy } from '../types/index.ts'

// Auto-generated by scripts/generate-showcase.cjs
// Run: npm run generate-showcase

export const SHOWCASE_TROPHIES: PublicTrophy[] = [
  {
    slug: 'sheenchair',
    name: 'Development Test Model',
    description: 'SheenChair.glb used for rendering validation during development.',
    modelPath: '/models/SheenChair.glb',
    thumbnailPath: '/images/placeholder.jpg',
    dimensions: { heightMm: 300, widthMm: 200, depthMm: 200 },
    materials: { primary: 'polishedGold' },
  },
  {
    slug: 'uefa-womens-euro-trophy-crystal-correctnormals',
    name: 'UEFA Womens Euro Trophy Crystal CorrectNormals',
    description: '',
    modelPath: '/models/UEFA-Womens-Euro-Trophy-Crystal-CorrectNormals.glb',
    thumbnailPath: '/images/UEFA-Womens-Euro-Trophy-Crystal-CorrectNormals.jpg',
    dimensions: { heightMm: 470, widthMm: 200, depthMm: 200 },
    materials: { primary: 'polishedSilver' },
    useOriginalMaterials: true,
  },
  {
    slug: 'uefa-womens-euro-trophy-silver-correctnormals',
    name: 'UEFA Womens Euro Trophy Silver CorrectNormals',
    description: '',
    modelPath: '/models/UEFA-Womens-Euro-Trophy-Silver-CorrectNormals.glb',
    thumbnailPath: '/images/UEFA-Womens-Euro-Trophy-Silver-CorrectNormals.jpg',
    dimensions: { heightMm: 470, widthMm: 200, depthMm: 200 },
    materials: { primary: 'polishedSilver' },
    useOriginalMaterials: true,
  }
]
